# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0a30b7aa0e62e03c06c431f9f17311b4"
application_url = "https://occurred-bio-wicked-academy.trycloudflare.com"
embedded = true
name = "Currency Converter"
handle = "currency-converter-vento"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
  uri = "/webhooks/compliance"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products"

[auth]
redirect_urls = [
  "https://occurred-bio-wicked-academy.trycloudflare.com/auth/callback",
  "https://occurred-bio-wicked-academy.trycloudflare.com/auth/shopify/callback",
  "https://occurred-bio-wicked-academy.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
