# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0a30b7aa0e62e03c06c431f9f17311b4"
application_url = "https://pattern-incorporate-ann-egypt.trycloudflare.com"
embedded = true
name = "Rabbi currency convertor"
handle = "Rabbi currency convertor"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://pattern-incorporate-ann-egypt.trycloudflare.com/auth/callback",
  "https://pattern-incorporate-ann-egypt.trycloudflare.com/auth/shopify/callback",
  "https://pattern-incorporate-ann-egypt.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
